server:
  port: 1299

spring:
  application:
    name: zuul-server

zuul:
  ignoredServices: '*'  #忽略所有，整个通过配置routes路由来访问
  routes:
    plat:
      path:  /plat/**   #平台服务的请求路径
      serviceId: plat-service
  prefix: /services   #请求前缀
