server:
  port: 9527
spring:
  application:
    name: product-server
  datasource:
    url: jdbc:mysql:///aigou-product
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver